/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DecouvrirRouteImport } from './routes/decouvrir'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AnalysesIdRouteImport } from './routes/analyses.$id'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirRoute = DecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesIdRoute = AnalysesIdRouteImport.update({
  id: '/analyses/$id',
  path: '/analyses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/dashboard': typeof DashboardRoute
  '/decouvrir': typeof DecouvrirRoute
  '/onboarding': typeof OnboardingRoute
  '/watchlists': typeof WatchlistsRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/dashboard': typeof DashboardRoute
  '/decouvrir': typeof DecouvrirRoute
  '/onboarding': typeof OnboardingRoute
  '/watchlists': typeof WatchlistsRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/dashboard': typeof DashboardRoute
  '/decouvrir': typeof DecouvrirRoute
  '/onboarding': typeof OnboardingRoute
  '/watchlists': typeof WatchlistsRoute
  '/analyses/$id': typeof AnalysesIdRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/categories/$slug': typeof CategoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/dashboard'
    | '/decouvrir'
    | '/onboarding'
    | '/watchlists'
    | '/analyses/$id'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/categories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/dashboard'
    | '/decouvrir'
    | '/onboarding'
    | '/watchlists'
    | '/analyses/$id'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/dashboard'
    | '/decouvrir'
    | '/onboarding'
    | '/watchlists'
    | '/analyses/$id'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/categories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  DashboardRoute: typeof DashboardRoute
  DecouvrirRoute: typeof DecouvrirRoute
  OnboardingRoute: typeof OnboardingRoute
  WatchlistsRoute: typeof WatchlistsRoute
  AnalysesIdRoute: typeof AnalysesIdRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir': {
      id: '/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof DecouvrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$id': {
      id: '/analyses/$id'
      path: '/analyses/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AnalysesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  DashboardRoute: DashboardRoute,
  DecouvrirRoute: DecouvrirRoute,
  OnboardingRoute: OnboardingRoute,
  WatchlistsRoute: WatchlistsRoute,
  AnalysesIdRoute: AnalysesIdRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
